# Generated by Django 4.1.7 on 2023-02-18 11:30

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name="Повне ім'я")),
                ('profession', models.TextField(max_length=50, verbose_name='Посада')),
                ('position', models.SmallIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to=main_page.models.Team.get_file_name, verbose_name='Фото')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Посада')),
            ],
            options={
                'verbose_name_plural': 'Наша команда',
                'ordering': ('position',),
            },
        ),
    ]
