# Generated by Django 4.1.7 on 2023-02-25 17:13

from django.db import migrations, models
import main_page.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заговок')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to=main_page.utils.get_file_name, verbose_name='Зображення')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
            ],
            options={
                'verbose_name_plural': 'Розклад занять',
                'ordering': ('position',),
            },
        ),
    ]
