# Generated by Django 4.1.7 on 2023-02-18 15:36

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва слайду')),
                ('position', models.SmallIntegerField(unique=True)),
                ('image', models.ImageField(upload_to=main_page.models.Slider.get_file_name, verbose_name='Зображення')),
                ('is_visible', models.BooleanField(default=True)),
                ('h_1', models.CharField(blank=True, max_length=250)),
                ('desc', models.TextField(blank=True, max_length=500)),
                ('tab_1', models.CharField(blank=True, max_length=50, verbose_name='Назва кнопки 1')),
                ('tab_1_url', models.URLField(blank=True)),
                ('tab_2', models.CharField(blank=True, max_length=50, verbose_name='Назва кнопки 1')),
                ('tab_2_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Слайдер',
                'ordering': ('position',),
            },
        ),
    ]
