# Generated by Django 4.1.7 on 2023-02-19 17:31

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=255, verbose_name='Текст заголовка')),
                ('desc', models.TextField(max_length=1000, verbose_name='Опис')),
                ('tab', models.CharField(max_length=55, verbose_name='Текст кнопки')),
                ('user', models.CharField(max_length=55, verbose_name="Ім'я засновника")),
                ('pos_user', models.CharField(max_length=55, verbose_name='Посада')),
                ('img_user', models.ImageField(upload_to=main_page.models.About.get_file_name, verbose_name='Зображення засновника')),
                ('is_visible', models.BooleanField(default=True)),
                ('img_1', models.ImageField(upload_to=main_page.models.About.get_file_name, verbose_name='Зображення дитини')),
                ('img_2', models.ImageField(upload_to=main_page.models.About.get_file_name, verbose_name='Зображення дитини')),
                ('img_3', models.ImageField(upload_to=main_page.models.About.get_file_name, verbose_name='Зображення дитини')),
            ],
            options={
                'verbose_name_plural': 'Ми про нас',
                'ordering': ('h1',),
            },
        ),
    ]
