# Generated by Django 4.1.7 on 2023-02-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_headlines'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headlines',
            options={'verbose_name_plural': 'Заголовки'},
        ),
        migrations.AlterField(
            model_name='headlines',
            name='desc_classes',
            field=models.TextField(blank=True, max_length=500, verbose_name='Текст classes '),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='desc_facilities',
            field=models.TextField(blank=True, max_length=500, verbose_name='Текст facilities'),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='desc_teachers',
            field=models.TextField(blank=True, max_length=500, verbose_name='Текст teachers'),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='desc_testimonial',
            field=models.TextField(blank=True, max_length=500, verbose_name='Текст testimonial'),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='title_classes',
            field=models.CharField(max_length=50, verbose_name='Заговок classes'),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='title_facilities',
            field=models.CharField(max_length=50, verbose_name='Заговок facilities'),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='title_teachers',
            field=models.CharField(max_length=50, verbose_name='Заговок teachers'),
        ),
        migrations.AlterField(
            model_name='headlines',
            name='title_testimonial',
            field=models.CharField(max_length=50, verbose_name='Заговок testimonial'),
        ),
    ]
