# Generated by Django 4.1.7 on 2023-02-19 18:32

from django.db import migrations, models
import django.db.models.deletion
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Назва')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('image', models.ImageField(blank=True, upload_to=main_page.models.Classes.get_file_name, verbose_name='Фото')),
                ('position', models.SmallIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='main_page.team')),
            ],
            options={
                'verbose_name_plural': 'Класи',
                'ordering': ('position',),
            },
        ),
    ]
