# Generated by Django 4.1.7 on 2023-02-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='age',
            field=models.CharField(default='3-5 Years', max_length=50, verbose_name='Вік'),
        ),
        migrations.AddField(
            model_name='classes',
            name='time',
            field=models.CharField(default='9-10 AM', max_length=50, verbose_name='Час початку занять'),
        ),
        migrations.AddField(
            model_name='classes',
            name='сapacity',
            field=models.CharField(default='30 Kids', max_length=50, verbose_name='Кількість в групі'),
        ),
    ]
