# Generated by Django 4.1.7 on 2023-02-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0005_team_fb_url_team_in_url_team_twi_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='in_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/', verbose_name='Посилання на LinkedIn'),
        ),
    ]
