# Generated by Django 4.1.7 on 2023-02-19 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_classes_age_classes_time_classes_сapacity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='сapacity',
            new_name='capacity',
        ),
    ]
