# Generated by Django 4.1.7 on 2023-02-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_team_in_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='in_url',
            field=models.URLField(blank=True, default='https://www.instagram.com/', verbose_name='Посилання на instagram'),
        ),
    ]
