# Generated by Django 4.1.7 on 2023-02-19 19:12

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_rename_сapacity_classes_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image_clas',
            field=models.ImageField(blank=True, upload_to=main_page.models.Team.get_file_name, verbose_name='Фото клас'),
        ),
    ]
