# Generated by Django 4.1.7 on 2023-02-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_team_image_clas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1_col_1', models.CharField(max_length=50, verbose_name='Назва колонка №1')),
                ('desc_col_1', models.TextField(max_length=255, verbose_name='Опис колонка №1')),
                ('h1_col_2', models.CharField(max_length=50, verbose_name='Назва колонка №2')),
                ('desc_col_2', models.TextField(max_length=255, verbose_name='Опис колонка №2')),
                ('h1_col_3', models.CharField(max_length=50, verbose_name='Назва колонка №3')),
                ('desc_col_3', models.TextField(max_length=255, verbose_name='Опис колонка №3')),
                ('h1_col_4', models.CharField(max_length=50, verbose_name='Назва колонка №4')),
                ('desc_col_4', models.TextField(max_length=255, verbose_name='Опис колонка №4')),
                ('position', models.SmallIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Шкільні зручності',
                'ordering': ('position',),
            },
        ),
    ]
