# Generated by Django 4.1.7 on 2023-02-21 17:09

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_facilities'),
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заговок')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, upload_to=main_page.models.Call.get_file_name, verbose_name='Зображення')),
                ('position', models.SmallIntegerField(unique=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('tab_1', models.CharField(blank=True, max_length=50, verbose_name='Текст кнопки')),
                ('tab_1_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Заклик',
                'ordering': ('position',),
            },
        ),
    ]
