# Generated by Django 4.1.7 on 2023-02-21 17:23

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_call'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=main_page.models.Gallery.get_file_name, verbose_name='Зображення')),
                ('position', models.SmallIntegerField(unique=True, verbose_name='Позиція')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Видимість')),
            ],
            options={
                'verbose_name_plural': 'Галерея',
                'ordering': ('position',),
            },
        ),
        migrations.AlterField(
            model_name='about',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимість'),
        ),
        migrations.AlterField(
            model_name='call',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимість'),
        ),
        migrations.AlterField(
            model_name='call',
            name='position',
            field=models.SmallIntegerField(unique=True, verbose_name='Позиція'),
        ),
        migrations.AlterField(
            model_name='call',
            name='tab_1_url',
            field=models.URLField(blank=True, verbose_name='Посилання'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимість'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='position',
            field=models.SmallIntegerField(unique=True, verbose_name='Позиція'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимість'),
        ),
        migrations.AlterField(
            model_name='facilities',
            name='position',
            field=models.SmallIntegerField(unique=True, verbose_name='Позиція'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='desc',
            field=models.TextField(blank=True, max_length=500, verbose_name='Опис'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='h_1',
            field=models.CharField(blank=True, max_length=250, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимість'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='position',
            field=models.SmallIntegerField(unique=True, verbose_name='Позиція'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tab_1_url',
            field=models.URLField(blank=True, verbose_name='Посилання 1'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='tab_2_url',
            field=models.URLField(blank=True, verbose_name='Посилання 2'),
        ),
        migrations.AlterField(
            model_name='team',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимість'),
        ),
        migrations.AlterField(
            model_name='team',
            name='position',
            field=models.SmallIntegerField(unique=True, verbose_name='Позиція'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Видимість'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='position',
            field=models.SmallIntegerField(unique=True, verbose_name='Позиція'),
        ),
    ]
