# Generated by Django 4.1.7 on 2023-02-21 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0011_gallery_alter_about_is_visible_alter_call_is_visible_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h1', models.CharField(max_length=50, verbose_name='Заговок')),
                ('address', models.CharField(max_length=50, verbose_name='Адреса')),
                ('phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Пошта')),
                ('twi_url', models.URLField(blank=True, verbose_name='Посилання на twitter')),
                ('fb_url', models.URLField(blank=True, verbose_name='Посилання на facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='Посилання на youtube')),
                ('in_url', models.URLField(blank=True, verbose_name='Посилання на LinkedIn')),
            ],
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ('position',), 'verbose_name': 'Фото', 'verbose_name_plural': 'Галерея'},
        ),
    ]
