# Generated by Django 4.1.7 on 2023-02-21 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0012_contacts_alter_gallery_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('child_name', models.CharField(max_length=50)),
                ('child_age', models.SmallIntegerField()),
                ('message', models.TextField(blank=True, max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('date_processing', models.DateField(auto_now=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Призначати зустріч',
                'ordering': ('-date',),
            },
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'ordering': ('h1',), 'verbose_name': 'Контакт', 'verbose_name_plural': 'Наші контакти'},
        ),
    ]
